site_name: TÖVE
nav:
  - API Documentation: docs/api/index.html
  - Features: features.md
  - Release Notes: release-notes.md
theme: readthedocs
markdown_extensions:
  - admonition
  - fenced_code
  - footnotes
  - tables
